// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ImmutableTree Version: 0.0.0.1
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Demo {
	using System.Diagnostics;
	using System.Linq;
	using ImmutableObjectGraph;
	
	public interface IFruit {
		System.String Color { get; }
		System.Int32 SkinThickness { get; }
	}
	
	public partial class Fruit : IFruit {
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private static readonly Fruit DefaultInstance = GetDefaultTemplate();
	
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private readonly System.String color;
	
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private readonly System.Int32 skinThickness;
	
		/// <summary>Initializes a new instance of the Fruit class.</summary>
		protected Fruit()
		{
		}
	
		/// <summary>Initializes a new instance of the Fruit class.</summary>
		protected Fruit(
			System.String color,
			System.Int32 skinThickness)
			: base()
		{
			this.color = color;
			this.skinThickness = skinThickness;
			this.Validate();
		}
	
		public static Fruit Create(
			ImmutableObjectGraph.Optional<System.String> color = default(ImmutableObjectGraph.Optional<System.String>),
			ImmutableObjectGraph.Optional<System.Int32> skinThickness = default(ImmutableObjectGraph.Optional<System.Int32>)) {
			return DefaultInstance.With(
				color: color.GetValueOrDefault(DefaultInstance.Color),
				skinThickness: skinThickness.GetValueOrDefault(DefaultInstance.SkinThickness));
		}
	
		public System.String Color {
			get { return this.color; }
		}
	
		public System.Int32 SkinThickness {
			get { return this.skinThickness; }
		}
		
		/// <summary>Returns a new instance with the Color property set to the specified value.</summary>
		public Fruit WithColor(System.String value) {
			if (value == this.Color) {
				return this;
			}
		
			return this.With(color: value);
		}
		
		/// <summary>Returns a new instance with the SkinThickness property set to the specified value.</summary>
		public Fruit WithSkinThickness(System.Int32 value) {
			if (value == this.SkinThickness) {
				return this;
			}
		
			return this.With(skinThickness: value);
		}
	
		/// <summary>Returns a new instance of this object with any number of properties changed.</summary>
		public virtual Fruit With(
			ImmutableObjectGraph.Optional<System.String> color = default(ImmutableObjectGraph.Optional<System.String>),
			ImmutableObjectGraph.Optional<System.Int32> skinThickness = default(ImmutableObjectGraph.Optional<System.Int32>)) {
			if (
				(color.IsDefined && color.Value != this.Color) || 
				(skinThickness.IsDefined && skinThickness.Value != this.SkinThickness)) {
				return new Fruit(
					color: color.GetValueOrDefault(this.Color),
					skinThickness: skinThickness.GetValueOrDefault(this.SkinThickness));
			} else {
				return this;
			}
		}
	
		/// <summary>Normalizes and/or validates all properties on this object.</summary>
		/// <exception type="ArgumentException">Thrown if any properties have disallowed values.</exception>
		partial void Validate();
	
		/// <summary>Provides defaults for fields.</summary>
		/// <param name="template">The struct to set default values on.</param>
		static partial void CreateDefaultTemplate(ref Template template);
	
		/// <summary>Returns a newly instantiated Fruit whose fields are initialized with default values.</summary>
		private static Fruit GetDefaultTemplate() {
			var template = new Template();
			CreateDefaultTemplate(ref template);
			return new Fruit(
				template.Color, 
				template.SkinThickness);
		}
	
		/// <summary>A struct with all the same fields as the containing type for use in describing default values for new instances of the class.</summary>
		private struct Template {
			internal System.String Color { get; set; }
	
			internal System.Int32 SkinThickness { get; set; }
		}
		
		public Builder ToBuilder() {
			return new Builder(this);
		}
		
		public partial class Builder {
			[DebuggerBrowsable(DebuggerBrowsableState.Never)]
			private Fruit immutable;
		
			[DebuggerBrowsable(DebuggerBrowsableState.Never)]
			protected System.String color;
		
			[DebuggerBrowsable(DebuggerBrowsableState.Never)]
			protected System.Int32 skinThickness;
		
			internal Builder(Fruit immutable) {
				this.immutable = immutable;
		
				this.color = immutable.Color;
				this.skinThickness = immutable.SkinThickness;
			}
		
			public System.String Color {
				get {
					return this.color;
				}
		
				set {
					this.color = value;
				}
			}
		
			public System.Int32 SkinThickness {
				get {
					return this.skinThickness;
				}
		
				set {
					this.skinThickness = value;
				}
			}
		
			public Fruit ToImmutable() {
				return this.immutable = this.immutable.With(
					ImmutableObjectGraph.Optional.For(this.Color),
					ImmutableObjectGraph.Optional.For(this.SkinThickness));
			}
		}
	}
}


